// -------------------------------------------------- //
// This file is autogenerated by pioasm; do not edit! //
// -------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// ------ //
// ps2kbd //
// ------ //

#define ps2kbd_wrap_target 0
#define ps2kbd_wrap 2

static const uint16_t ps2kbd_program_instructions[] = {
            //     .wrap_target
    0x2021, //  0: wait   0 pin, 1                   
    0x4001, //  1: in     pins, 1                    
    0x20a1, //  2: wait   1 pin, 1                   
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program ps2kbd_program = {
    .instructions = ps2kbd_program_instructions,
    .length = 3,
    .origin = -1,
};

static inline pio_sm_config ps2kbd_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + ps2kbd_wrap_target, offset + ps2kbd_wrap);
    return c;
}
#endif

